# fly.toml app configuration file generated for bot-discord-red-resonance-8984 on 2024-08-07T11:02:23-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bot-discord-red-resonance-8984'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
